---

- hosts: localhost
  connection: local
  gather_facts: no
  roles:
    - role: cloudformation-rancher
      

- name: Deploy Rancher agents
  hosts: rancher-agent
  become: yes
  roles:
    - role: rancher-agent
      rancher_host: "{{ rancher_endpoint }}"
      rancher_project_token: "{{rancher_agent_clusters[agent_profile].rancher_project_token}}"
      rancher_agent_tags: "{{rancher_agent_clusters[agent_profile].rancher_agent_tags}}"