---

- hosts: localhost
  connection: local
  gather_facts: no
  roles:
    - role: cloudformation-rancher
      inventory_groups: rancher-dev

- hosts: localhost
  connection: local
  gather_facts: no
  roles:
    - role: sshconfig
      bastion_host : "{{hostvars[groups['rancher-bastion'][0]]['ec2_ip_address']}}"
      when: "({{groups['rancher-bastion'] | length}} > 0 | bool)"

- hosts: rancher
  tags: ensurepython
  gather_facts: False
  tasks:
  - name: Ensure python is installed
    raw: sudo bash -c "test -e /usr/bin/python || (apt -qqy update && apt install -qy python-minimal)"

- name: Install common packages
  hosts: rancher
  gather_facts: yes
  become: yes
  roles:
    - role: common
      inventory_groups: rancher-dev      

- name: Install Docker
  hosts: rancher-server:rancher-agent
  become: yes
  roles:
    - angstwad.docker_ubuntu


- name: Setup Rancher HA
  hosts: rancher-server
  become: yes
  roles:
    - role: rancher-ha
      rancher_host: rancherdev.io.nuxeo.com
      mysql_host: "{{ hostvars['localhost']['cf_rancher'].stack_outputs.DBHost}}"
      mysql_port: "{{ hostvars['localhost']['cf_rancher'].stack_outputs.DBPort}}"
      mysql_username: rancher
      mysql_password: rancherpassword

- name: Deploy Rancher agents
  hosts: rancher-agent
  become: yes
  roles:
    - role: rancher-agent
      rancher_host: rancherdev.io.nuxeo.com