---

- hosts: localhost
  connection: local
  gather_facts: no
  roles:
    - role: cloudformation-rancher

- hosts: rancher:!cloudformation
  gather_facts: False
  tasks:
  - name: Ensure python is installed
    raw: sudo bash -c "test -e /usr/bin/python || (apt -qqy update && apt install -qy python-minimal)"

- name: Install common packages
  hosts: rancher-dev:!cloudformation
  gather_facts: yes
  become: yes
  roles:
    - role: common      

- name: Install Docker
  hosts: rancher-server:rancher-agent
  become: yes
  roles:
    - angstwad.docker_ubuntu


- name: Setup Rancher HA
  hosts: rancher-server
  become: yes
  roles:
    - role: rancher-ha
      rancher_host: rancherdev.io.nuxeo.com
      mysql_host: "{{ hostvars['localhost']['cf_rancher'].stack_outputs.DBHost}}"
      mysql_port: "{{ hostvars['localhost']['cf_rancher'].stack_outputs.DBPort}}"
      mysql_username: rancher
      mysql_password: rancherpassword
