---


- name: Rancher database creation
  mysql_db:
    name: cattle
    login_host: "{{ mysql_host }}"
    login_port: "{{ mysql_port }}"
    login_user: rancher
    login_password: rancherpassword
  when: inventory_hostname == groups["rancher-server"][0] 

- name: Launch Rancher docker container
  docker_container:
    name: rancher-ha
    image: rancher/server
    command: --db-host {{ mysql_host }} --db-port {{ mysql_port }} --db-user rancher --db-pass rancherpassword --db-name cattle --advertise-address {{ ansible_default_ipv4.address }}
    state: started
    recreate: yes
    published_ports:
      - 9345:9345
      - 8080:8080


- name: Wait for Rancher HA to be available
  wait_for: host={{inventory_hostname}} port=80 timeout=600 state=started

