---

- name: Start rancher agents
  docker:    
    image: rancher/agent
    state: reloaded
    pull: always
    privileged: true
    command: "https://{{rancher_host}}/v1/scripts/{{rancher_project_token}}"
    env:      
      CATTLE_AGENT_IP: "{{ ansible_default_ipv4.address }}"
      CATTLE_HOST_LABELS: "{{ rancher_agent_tags }}"  
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/rancher:/var/lib/rancher
  
